### PR TITLE
Fixes #16

### LINKED ISSUE #16: failed on 32-bit tests
https://ci.appveyor.com/project/MaidSafe-QA/memory-map/build/1.0.5

### PR DESCRIPTION
**Pull request by Fraser999**

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -67,6 +63,7 @@ impl Protection {
 
     /// Returns `true` if the `Protection` is writable.
     pub fn write(self) -> bool {
+        use Protection::*;
```
Comment (dirvine) [inline src/lib.rs]: Ah nice

File: src/windows.rs [hunk 2]
```diff
@@ -38,6 +40,7 @@ pub struct MmapInner {
 
 impl MmapInner {
 
+    #[allow(trivial_numeric_casts)]
```
Comment (dirvine) [inline src/windows.rs]: Unfortunate here, we probably need to dig deeper soon, but good for now.
